=== gitpan/InSilicoSpectro/t/InSilico/data/rtset.dtd
<!ELEMENT rtsettings (Hodges?,Petritis?,calibrator?,filtering?)>
    <!ELEMENT Hodges  (modif?,current?,overwrite?,comments?)>
      <!ELEMENT modif  (#PCDATA)>
      <!ELEMENT current  (#PCDATA)>
      <!ELEMENT overwrite      (#PCDATA)>
      <!ELEMENT comments      (#PCDATA)>
    <!ELEMENT Petritis  (maxepoch?,sqrerror?,node?,nnet?,layer*)>
      <!ELEMENT maxepoch  (#PCDATA)>
      <!ELEMENT sqrerror  (#PCDATA)>
      <!ELEMENT mode      (#PCDATA)>
      <!ELEMENT nnet (learningrate?,randomconnections?,randomweights?,bias?,momentum?)>
        <!ELEMENT learningrate (#PCDATA)>
        <!ELEMENT randomconnections (#PCDATA)>
        <!ELEMENT randomweights (#PCDATA)>
        <!ELEMENT bias (#PCDATA)>
        <!ELEMENT momentum (#PCDATA)>
      <!ELEMENT layer (nodes,persistentactivation?,decay?,randomactivation?,threshold?,activationfunction?)>
        <!ELEMENT nodes (#PCDATA)>
        <!ELEMENT persistentactivation (#PCDATA)>
        <!ELEMENT decay (#PCDATA)>
        <!ELEMENT randomactivation (#PCDATA)>
        <!ELEMENT threshold (#PCDATA)>
        <!ELEMENT activationfunction (#PCDATA)>
  <!ELEMENT calibrator (preprocess?,fitting,gamma?)>
     <!ELEMENT preprocess  (#PCDATA)>
     <!ELEMENT fitting  (#PCDATA)>
     <!ELEMENT gamma  (#PCDATA)>
  <!ELEMENT filtering (filter?,error?)>
     <!ELEMENT filter  (#PCDATA)>
     <!ELEMENT error   (#PCDATA)>

=== gitpan/InSilicoSpectro/t/InSilico/data/rtset.xml
<?xml version="1.0"?>
<!-- Additional settings file for the retention time predictor -->
<!DOCTYPE rtsettings SYSTEM "rtset.dtd">

<rtsettings>
  <Hodges>
    <modif>0</modif>
    <current>LinRegGB</current>
    <overwrite>1</overwrite>
    <comments>Test</comments>
  </Hodges>
 <Petritis>
    <maxepoch>50</maxepoch>
    <sqrerror>1e-3</sqrerror>
    <mode>verbose</mode>
    <nnet>
      <learningrate>0.5</learningrate>
    </nnet>
    <layer>
      <nodes>20</nodes>
    </layer>
    <layer>
      <nodes>6</nodes>
    </layer>
    <layer>
      <nodes>1</nodes>
    </layer>
  </Petritis>
  <calibrator>
     <preprocess>1</preprocess>
     <fitting>linear</fitting>
     <gamma>1e-6</gamma>
  </calibrator>
  <filtering>
      <filter>10</filter>
      <error>relative</error>
  </filtering>
</rtsettings>
